import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const graphik = localFont({
  src: "./fonts-graphik-regular-web.woff2",
  weight: "400",
  variable: "--font-graphik",
});

export const metadata = {
  title: "First Demat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${graphik.variable} ${graphik.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}